name: flutter_instagram_feed
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  phosphor_flutter: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0

flutter_gen:
  output: lib/core/assets
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.svg

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter.ttf
